"""add_route_images_and_new_fields

Revision ID: 4424a3d89edd
Revises: dd40eb7fe56e
Create Date: 2026-04-01 12:42:11.334740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4424a3d89edd'
down_revision: Union[str, None] = 'dd40eb7fe56e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('route_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('public_id', sa.String(length=500), nullable=True),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('is_cover', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['route_id'], ['routes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_images_id'), 'route_images', ['id'], unique=False)
    op.add_column('routes', sa.Column('success_rate', sa.String(length=50), nullable=True))
    op.add_column('routes', sa.Column('max_altitude', sa.String(length=100), nullable=True))
    op.add_column('routes', sa.Column('distance', sa.String(length=100), nullable=True))
    op.add_column('routes', sa.Column('group_size', sa.String(length=100), nullable=True))
    op.add_column('routes', sa.Column('best_season', sa.String(length=255), nullable=True))
    op.add_column('routes', sa.Column('highlights', sa.JSON(), nullable=True))
    op.add_column('routes', sa.Column('itinerary', sa.JSON(), nullable=True))
    op.add_column('routes', sa.Column('included', sa.JSON(), nullable=True))
    op.add_column('routes', sa.Column('excluded', sa.JSON(), nullable=True))
    op.add_column('routes', sa.Column('packing_list', sa.JSON(), nullable=True))
    op.add_column('routes', sa.Column('is_published', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('routes', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    op.add_column('routes', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, server_default=sa.text('now()')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routes', 'updated_at')
    op.drop_column('routes', 'created_at')
    op.drop_column('routes', 'is_published')
    op.drop_column('routes', 'packing_list')
    op.drop_column('routes', 'excluded')
    op.drop_column('routes', 'included')
    op.drop_column('routes', 'itinerary')
    op.drop_column('routes', 'highlights')
    op.drop_column('routes', 'best_season')
    op.drop_column('routes', 'group_size')
    op.drop_column('routes', 'distance')
    op.drop_column('routes', 'max_altitude')
    op.drop_column('routes', 'success_rate')
    op.drop_index(op.f('ix_route_images_id'), table_name='route_images')
    op.drop_table('route_images')
    # ### end Alembic commands ###
